name: cleanarch
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  http: ^1.1.0
  rxdart: ^0.27.7
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.2.5
  intl: ^0.19.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
